name: ELT Pipeline for Starlink Prediction

on:
  workflow_dispatch:  # Triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure ELT pipeline for Starlink Prediction
      run: |
        echo "=== Configuring ELT pipeline for starlink prediction ===\n\n"
        cp -f default_meltano.yml elt_pipeline/meltano.yml
        
        # Install python dependencies
        echo "=== Installing python dependencies ===\n"
        cd elt_pipeline
        rm -f plugins/loaders/target-postgres--meltanolabs.lock plugins/utilities/dbt-postgres--dbt-labs.lock starlink_prediction.csv
        python3 -m pip install --no-cache-dir -r requirements.txt

        # Add extractor tap-spacexapi 
        echo "=== Adding tap-spacexapi extractor ===\n"
        meltano add --from-ref tap-spacexapi.yml extractor tap-spacexapi

        # Add loader target-postgres to meltano
        # First run local docker container with postgres
        echo "=== Start docker container with postgres in local ===\n"
        # Stop and remove container if already exists
        docker stop meltano_postgres || true && docker rm -f meltano_postgres || true
        docker-compose up -d

        echo "=== Adding target-postgres loader ===\n"
        meltano add loader target-postgres --variant=meltanolabs
        meltano config target-postgres set user meltano
        meltano config target-postgres set password password
        meltano config target-postgres set database postgres
       
