name: ELT Pipeline for Starlink Prediction

on:
  workflow_dispatch:  # Triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure ELT pipeline for Starlink Prediction
      run: |
        echo "=== Configuring ELT pipeline for starlink prediction ===\n\n"
        cp -f default_meltano.yml elt_pipeline/meltano.yml
        
        # Install python dependencies
        echo "=== Installing python dependencies ===\n"
        cd elt_pipeline
        rm -f plugins/loaders/target-postgres--meltanolabs.lock plugins/utilities/dbt-postgres--dbt-labs.lock starlink_prediction.csv
        python3 -m pip install --no-cache-dir -r requirements.txt

    - name: Add Custom Spacex API Extractor
      run: |
        cd elt_pipeline
        # Add extractor tap-spacexapi 
        echo "=== Adding tap-spacexapi extractor ===\n"
        meltano add --from-ref tap-spacexapi.yml extractor tap-spacexapi

    - name: Start Docker Container with Postgres
      run: |
        cd elt_pipeline
        echo "=== Start docker container with postgres in local ===\n"
        docker-compose up -d

    - name: Add Postgres Loader
      run: |
        cd elt_pipeline
        echo "=== Adding target-postgres loader ===\n"
        meltano add loader target-postgres --variant=meltanolabs
        meltano config target-postgres set user meltano
        meltano config target-postgres set password password
        meltano config target-postgres set database postgres
        meltano config target-postgres set add_record_metadata True
        meltano config target-postgres set host localhost  

    - name: Add dbt-postgres Utility
      run: |
        cd elt_pipeline
        echo "=== Adding dbt-postgres utility ===\n"
        meltano add utility dbt-postgres
        meltano invoke dbt-postgres:initialize
        meltano config dbt-postgres set host localhost
        meltano config dbt-postgres set port 5432
        meltano config dbt-postgres set user meltano
        meltano config dbt-postgres set password password
        meltano config dbt-postgres set dbname postgres
        meltano config dbt-postgres set schema analytics

    - name: Fix Bug in dbt-postgres
      run: |
        cd elt_pipeline
        echo "=== Fix dbt-postgres bug ===\n"
        python3 fix_clean-targets.py

    - name: Add Meltano Jobs to run the pipeline
      run: |
        cd elt_pipeline
        echo "=== Add meltano jobs for ELT pipeline ===\n"
        meltano job add extract_and_load_data --tasks "tap-spacexapi target-postgres"
        meltano job add transform_data --tasks "dbt-postgres:run"
        meltano job add dbt_tests --tasks "dbt-postgres:test"
        meltano job add generate_dbt_docs --tasks "dbt-postgres:docs-generate"

    - name: Run the ELT Pipeline
      run: |
        cd elt_pipeline
        echo "\n\n"
        echo "==========================================="
        echo "Running the ELT pipeline, predicting starlink launches!..."
        meltano run extract_and_load_data transform_data dbt_tests generate_dbt_docs
    
    - name: Run the prediction script!
      run: |

        python3 starlink_prediction/prediction.py
        echo "Pipeline successfully completed!"
        echo "==========================================="
